version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=promptsnap
    volumes:
      - mongodb_data:/data/db
      - ./mongo-seed.js:/docker-entrypoint-initdb.d/mongo-seed.js:ro

volumes:
  mongodb_data: